#include "display.h"

void display_init(void){
    DIR_segA = OUT;
    DIR_segB = OUT;
    DIR_segC = OUT;
    DIR_segD = OUT;
    DIR_segE = OUT;
    DIR_segF = OUT;
    DIR_segG = OUT;
}
void display_init2(void){
    DIR_segA2 = OUT;
    DIR_segB2 = OUT;
    DIR_segC2 = OUT;
    DIR_segD2 = OUT;
    DIR_segE2 = OUT;
    DIR_segF2 = OUT;
    DIR_segG2 = OUT;
}
void display_ac (char dig){
    switch(dig){
        case 0: segA = 0;
                segB = 0;
                segC = 0;
                segD = 0;
                segE = 0;
                segF = 0;
                segG = 1;
                break;
        case 1: segA = 1;
                segB = 0;
                segC = 0;
                segD = 1;
                segE = 1;
                segF = 1;
                segG = 1;
                break; 
        case 2: segA = 0;
                segB = 0;
                segC = 1;
                segD = 0;
                segE = 0;
                segF = 1;
                segG = 0;
                break;     
        case 3: segA = 0;
                segB = 0;
                segC = 0;
                segD = 0;
                segE = 1;
                segF = 1;
                segG = 0;
                break;     
        case 4: segA = 1;
                segB = 0;
                segC = 0;
                segD = 1;
                segE = 1;
                segF = 0;
                segG = 0;
                break;     
        case 5: segA = 0;
                segB = 1;
                segC = 0;
                segD = 0;
                segE = 1;
                segF = 0;
                segG = 0;
                break;     
        case 6: segA = 0;
                segB = 1;
                segC = 0;
                segD = 0;
                segE = 0;
                segF = 0;
                segG = 0;
                break;   
        case 7: segA = 0;
                segB = 0;
                segC = 0;
                segD = 1;
                segE = 1;
                segF = 1;
                segG = 1;
                break;     
        case 8: segA = 0;
                segB = 0;
                segC = 0;
                segD = 0;
                segE = 0;
                segF = 0;
                segG = 0;
                break;     
        case 9: segA = 0;
                segB = 0;
                segC = 0;
                segD = 1;
                segE = 1;
                segF = 0;
                segG = 0;
                break;     
                
    }
}
void display_ac2 (char dig){
    switch(dig){
        case 0: segA2 = 0;
                segB2 = 0;
                segC2 = 0;
                segD2 = 0;
                segE2 = 0;
                segF2 = 0;
                segG2 = 1;
                break;
        case 1: segA2 = 1;
                segB2 = 0;
                segC2 = 0;
                segD2 = 1;
                segE2 = 1;
                segF2 = 1;
                segG2 = 1;
                break; 
        case 2: segA2 = 0;
                segB2 = 0;
                segC2 = 1;
                segD2 = 0;
                segE2 = 0;
                segF2 = 1;
                segG2 = 0;
                break;     
        case 3: segA2 = 0;
                segB2 = 0;
                segC2 = 0;
                segD2 = 0;
                segE2 = 1;
                segF2 = 1;
                segG2 = 0;
                break;     
        case 4: segA2 = 1;
                segB2 = 0;
                segC2 = 0;
                segD2 = 1;
                segE2 = 1;
                segF2 = 0;
                segG2 = 0;
                break;     
        case 5: segA2 = 0;
                segB2 = 1;
                segC2 = 0;
                segD2 = 0;
                segE2 = 1;
                segF2 = 0;
                segG2 = 0;
                break;     
        case 6: segA2 = 0;
                segB2 = 1;
                segC2 = 0;
                segD2 = 0;
                segE2 = 0;
                segF2 = 0;
                segG2 = 0;
                break;   
        case 7: segA2 = 0;
                segB2 = 0;
                segC2 = 0;
                segD2 = 1;
                segE2 = 1;
                segF2 = 1;
                segG2 = 1;
                break;     
        case 8: segA2 = 0;
                segB2 = 0;
                segC2 = 0;
                segD2 = 0;
                segE2 = 0;
                segF2 = 0;
                segG2 = 0;
                break;     
        case 9: segA2 = 0;
                segB2 = 0;
                segC2 = 0;
                segD2 = 1;
                segE2 = 1;
                segF2 = 0;
                segG2 = 0;
                break;     
                
    }
}